import localFont from "next/font/local";
import "./globals.css";
import NeonBackground from "./Styles/NeonBackground";
import Header from "./_components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NeonBackground />
        <div className="flex">
          <div className="w-3/6">
            < Header />
          </div>
          <div className="w-3/6">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}

